### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/DockerizeMe#1]

**Comment by mrajashree** [comment]
This is a proposal for the 'Dockerize me' application. The idea comes from the Netflix-AWS partnership, due to which Netflix is able to provide seemless or continuous global service. Using AWS, Netflix can deploy a huge number of servers within minutes. We intend to introduce docker containers in place of these AWS instances, since the containers would be running on a single host, as compared to multiple AWS instances running on different hosts.

**Comment by chrisparnin** [comment]
As companies are migrated from on-premise products delivered to customer sites, to hosted software applications, they have been finding cost effective ways to host software

One approach has been to place services in virtual machines to ease the ability to scale on cloud providers such as AWS. However, an alternative approach is to deploy applications in lighter-weight containers. Docker allows services to be isolated in a standalone containers which can be provisioned and run with less overhead than full virtual machine images. Porting traditional applications to run within docker containers is not always so easy. Docker containers often require that the applications remain stateless. This means if two services needed to interact via the file system, then some degree of porting must occur.

DockerizeMe attempts to make this porting process easier. We support

* 1) porting dependencies into the docker image. 
* 2) handling simple cases of file system access mapping between two services. 
* 3) Support building this process automatically from a build server (Jenkins) or via web hooks.

Some tasks, include ….

**Comment by mrajashree** [comment]
Project description:
As companies are migrating from on-premise software to hosted software applications, they have been finding cost-effective ways to host software more efficiently.
Virtualization using cloud providers such as AWS is one approach to hosting software effectively. One other approach that has gained a lot more popularity is using docker containers. Docker containers are light-weight. Docker allows services to be isolated in a standalone container which can be provisioned and run with less overhead than full virtual machine images, leading to higher resource utilization. Porting traditional applications to run within docker containers is not always so easy. Docker containers often require that the applications remain stateless. This means if two services needed to interact via the file system, then some degree of porting must occur.
DockerizeMe attempts to make this porting process easier. We support
1. porting dependencies into the docker image.
2. handling simple cases of file system access mapping between two services.
3. Support building this process automatically from a build server (Jenkins) or via web hooks.

Project phases:
1. Identify the dependencies for the application to be dockerized, and decide number of containers
2. Build a docker image
3. Provide docker cross container communication for necessary services
4. Test if the application is running as expected on the containers
5. Write github-webhooks to automate this process using continuous integration tool (eg, Jenkins)

Implementation:
Research on the actual benefits and limitations when using docker for the application under consideration would be the first step. Then we will decide on the number of containers needed for the project and create a docker image. Creating and maintaining stateless containers, and one container for storing persistent state of the application would come next. We will enable docker cross container communication. Then we will test if the application is running as expected.

Possible challenges:
1. Correctly identifying all dependencies
2. Establishing successful docker cross container communication
