### ISSUE TITLE
Sample projects

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/DockerizeMe#4]
Locate a couple of sample projects to work with in each technology stack. Put a link to the repo in comment.

* Popular tools on github
* Pick a range of complexity.
* It has to have a package manager
* Ideally, some with unit tests.
* Work in linux, mostly command line driven.

**Comment by mrajashree** [comment]
1. JavaScript: https://github.com/jsonschema/json-schema-v2
2. Python: https://github.com/aptxkid/popular_github_repo_finder
3. Java: https://github.com/apache/commons-math
