### ISSUE TITLE
Start with a simple node.js app

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/DockerizeMe#5]
```
dockerizeme https://github.com/CSC-DevOps/App.git
```
* Have it accept basic command line arguments (`args = process.argv.slice(2)`)
* Simply have it clone a repo
* Run a simple prediction on repo and print out guessed repo.

**Comment by mrajashree** [comment]
A node.js app called detect_technology.js is now accepting repo URL as argument and predicting its language
